ITNews/Models/ErrorViewModel.cs
using System;

namespace ITNews.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ITNews/Areas/Admin/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ITNews.Areas.Admin.Controllers
{
    //[Route("admin/[controller]")]
    [Area("Admin")]
    public class AdminController : Controller
    {
        //[Authorize(Roles = "admin")]
        [Route("[area]/[controller]/[action]")]
        public IActionResult Index()
        {
            return View();
        }

        [Route("[area]/[controller]/[action]")]
        public IActionResult Profile()
        {
            return View();
        }
    }
}

ITNews/Controllers/AuthorizeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace ITNews.Controllers
{
    public class AuthorizeController : Controller
    {
        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Registration()
        {
            return View();
        }
    }
}

ITNews/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ITNews.Models;

namespace ITNews.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ITNews/Controllers/MySpaceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace ITNews.Controllers
{
    public class MySpaceController : Controller
    {
        public IActionResult MyNews()
        {
            return View();
        }

        public IActionResult PersanalData()
        {
            return View();
        }
    }
}

ITNews/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace ITNews.Controllers
{
    public class NewsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult AddNews()
        {
            return View();
        }

        public IActionResult News()
        {
            return View();
        }
    }
}

ITNews/Areas/Admin/Views/Admin/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";//"~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Users</h2>

<div id="adminUserListDiv">
    <div class="list-group customListGroupWithBtns">
        <!--

        <a v-bind:href="item.url" v-for="item in users" class="list-group-item list-group-item-action">
            {{item.email}}
        </a>
        <button v-for="item in users" v-on:click="openUserProfileClick(item)" type="button" class="list-group-item list-group-item-action">
            {{item.email}}
        </button>
    -->
        <div class="custumGroup-withButn">
            <div v-for="item in users" class="custumGroupItem-withButn">
                <div class="btn-group" role="group" aria-label="Button group with nested dropdown">
                    <button v-on:click="openUserProfileClick(item)" type="button" class="btn">{{item.email}}</button>
                    <button v-on:click="deleteUserClick(item)" type="button" class="btn">&times;</button>
                </div>
            </div>
        </div>
    </div>
    <br />
</div>

<script src="~/js/Areas/Admin/AdminService.js"></script>
<script src="~/js/Areas/Admin/Users.js"></script>
<script src="~/js/base/loader.js"></script>
<script src="~/js/user/UsersHub.js"></script>

<script>
    $(document).ready(function () {
        let loader = new Loader({ getActionsUrl: domainPath + '/api/admin/getActions' });
        loader.getActions()
            .done(function (data) {
                let service = new AdminService(data.actions);
                let viewModel = new UsersViewModel(service);
                viewModel.usersVue.initialize();
            });

    })
</script>

ITNews/Areas/Admin/Views/Admin/Profile.cshtml
@{
    ViewData["Title"] = "Profile";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Profile</h2>

@{Html.RenderPartial("_UserProfile");}

<script src="~/js/user/User.js"></script>
<script src="~/js/user/UserProfileViewModel.js"></script>
<script src="~/js/Areas/Admin/UserProfileService.js"></script>
<script src="~/js/base/loader.js"></script>
<script src="~/js/user/Role.js"></script>

<script>
    $(document).ready(function () {
        let loader = new Loader({ getActionsUrl: domainPath + '/api/admin/GetActions' });
        loader.getActions()
            .done(function (data) {
                let service = new UserProfileService(data.actions);
                let viewModel = new UserProfileViewModel(service);
                viewModel.persanalDataVue.initialize();
            });
    })
</script>

ITNews/Areas/Admin/Views/Admin/View.cshtml
@{
    ViewData["Title"] = "View";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>View</h2>

ITNews/Areas/Admin/Views/Shared/_AdminLayout.cshtml
@{
    ViewData["Title"] = "AdminLayout";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-2">
        <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
            <a class="nav-link active" id="v-pills-home-tab" data-toggle="pill" href="#v-pills-home" role="tab" aria-controls="v-pills-home" aria-selected="true">Home</a>
            <a class="nav-link" id="v-pills-profile-tab" data-toggle="pill" href="#v-pills-profile" role="tab" aria-controls="v-pills-profile" aria-selected="false">Profile</a>
            <a class="nav-link" id="v-pills-messages-tab" data-toggle="pill" href="#v-pills-messages" role="tab" aria-controls="v-pills-messages" aria-selected="false">Messages</a>
            <a class="nav-link" id="v-pills-settings-tab" data-toggle="pill" href="#v-pills-settings" role="tab" aria-controls="v-pills-settings" aria-selected="false">Settings</a>
        </div>
        <div class="tab-content" id="v-pills-tabContent">
            <div class="tab-pane fade show active" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab">
                @RenderBody()
            </div>
            <div class="tab-pane fade" id="v-pills-profile" role="tabpanel" aria-labelledby="v-pills-profile-tab">...</div>
            <div class="tab-pane fade" id="v-pills-messages" role="tabpanel" aria-labelledby="v-pills-messages-tab">...</div>
            <div class="tab-pane fade" id="v-pills-settings" role="tabpanel" aria-labelledby="v-pills-settings-tab">...</div>
        </div>
    </div>
    <div class="col-md-10">
    </div>
</div>

<div class="container">
</div>

ITNews/Views/Authorize/Login.cshtml
@{
    ViewData["Title"] = "Login";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Login</h1>

<div id="loginform">
    <form>
        <div class="form-group row">
            <label for="inputEmail" class="col-sm-2 col-form-label">Email</label>
            <div class="col-sm-10">
                <input v-model="user.email" type="text" class="form-control" id="inputEmail" placeholder="email@example.com">
            </div>
        </div>
        <div class="form-group row">
            <label for="inputPassword" class="col-sm-2 col-form-label">Password</label>
            <div class="col-sm-10">
                <input v-model="user.password" type="password" class="form-control" id="inputPassword" placeholder="Password">
            </div>
        </div>
        <input type="button" class="btn btn-secondary" name="Login" value="LogIn" v-on:click="logIn"/>
    </form>
</div>

<script src="~/js/user/User.js"></script>
<script src="~/js/authorize/authorizeService.js"></script>
<script src="~/js/authorize/login.js"></script>

<script>
    jQuery(document).ready(function () {
        debugger;
        var loader = new Loader({ getActionsUrl: domainPath + '/api/Authorize/getActions' });
        loader.getActions().done(function (data) {
            let service = new AuthorizeService(data.actions);
            let viewModel = new LoginViewModel(service);
        })
    })
</script>

ITNews/Views/Authorize/Registration.cshtml
@{
    ViewData["Title"] = "Registration";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Registration</h1>

<form id="registrationForm">
    <div class="form-group row">
        <label for="staticEmail" class="col-sm-2 col-form-label">Email</label>
        <div class="col-sm-10">
            <input type="text" v-model="user.email" class="form-control" id="inputEmail" placeholder="email@example.com">
        </div>
    </div>
    <div class="form-group row">
        <label for="inputPassword" class="col-sm-2 col-form-label">Password</label>
        <div class="col-sm-10">
            <input type="password" v-model="user.password" class="form-control" placeholder="Password">
        </div>
    </div>
    <div class="form-group row">
        <label for="inputPassword" class="col-sm-2 col-form-label">Confirm Password</label>
        <div class="col-sm-10">
            <input type="password" class="form-control" placeholder="Password">
        </div>
    </div>
    <input type="button" class="btn btn-secondary" name="registration" value="registration" v-on:click="registration" />
</form>

<script src="~/js/user/User.js"></script>
<script src="~/js/authorize/authorizeService.js"></script>
<script src="~/js/authorize/registration.js"></script>

<script>
    $(document).ready(function () {
        $('#inputEmail').focus();

        var loader = new Loader({ getActionsUrl: domainPath + '/api/Authorize/getActions' });
        loader.getActions().done(function (data) {
            let service = new AuthorizeService(data.actions);
            let viewModel = new RegistrationViewModel(service);
        })
    })
</script>

ITNews/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ITNews/Views/MySpace/MyNews.cshtml
@{
    ViewData["Title"] = "MyNews";
}
<link href="~/css/mySpace/myNews.css" rel="stylesheet" />
<h1>MyNews</h1>

@{ Html.RenderPartial("~/Views/News/_NewsListPartial.cshtml");}

<!--
<script src="~/js/markDown/MarkDownHelper.js"></script>

<script src="~/js/markDown/ace/1.1.3/ace.js"></script>
<script src="~/js/markDown/ace/1.1.3/ext-language_tools.js"></script>
<script src="~/js/markDown/ace/1.1.3/mode-markdown.js"></script>
<script src="~/js/markDown/ace/1.1.3/theme-tomorrow.js"></script>
<script src="~/js/markDown/marked/0.3.2/marked.min.js"></script>
<script src="~/js/markDown/jquery/2.1.3/jquery.min.js"></script>

<link href="~/css/markDown/bootstrap-markdown-editor.css" rel="stylesheet">
<script src="~/lib/bootstap_3.3.1/js/bootstrap.min.js"></script>
<script src="~/js/markDown/bootstrap-markdown-editor.js"></script>
-->


<script>
    jQuery(document).ready(function ($) {
        let loader = new Loader({ getActionsUrl: domainPath + '/api/news/getActions' });
        loader.getActions()
            .done(function (data) {
                let service = new NewsService(data.actions);
                let viewModel = new NewsViewModel(service);
                viewModel.newsVue.userForFilter = sessionStorage.getItem('currentUserId');
                viewModel.newsVue.initialize();
            });
    });
</script>

ITNews/Views/MySpace/PersanalData.cshtml
@{
    ViewData["Title"] = "PersanalData";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Persanal Data</h1>

@{ Html.RenderPartial("_UserProfile");}

<script src="~/js/user/User.js"></script>
<script src="~/js/user/UserProfileViewModel.js"></script>
<script src="~/js/Areas/Admin/UserProfileService.js"></script>
<script src="~/js/base/loader.js"></script>
<script src="~/js/user/Role.js"></script>
<!--
  <div id="persanaldataContainer" class="row">
    <div class="col-md-4">
        <img src="~/icon/man_default_avatar.png" class="img-circle" alt="Cinque Terre">
    </div>
    <div class="col-md-8">
        <div class="form-group">
            <label for="inputEmail" class="col-form-label">Email</label>
            <input id="inputEmail" v-model="user.email"
                   class="form-control" type="text" name="name" value="" placeholder="email@example.com" />
        </div>
        <div class="form-group">
            <label for="inputPassword" class="col-form-label">Password</label>
            <input id="inputPassword" v-model="user.password"
                   class="form-control" type="password" name="name" value="" placeholder="password" />
        </div>
        <div class="form-group">
            <label for="inputName" class="col-form-label">Name</label>
            <input id="inputName" v-model="user.name"
                   class="form-control" type="text" name="name" value="" placeholder="Your name" />
        </div>
        <input type="button" class="btn btn-secondary" name="name" value="Apply" v-on:click="saveUser" />
    </div>
</div>



<script src="~/js/user/User.js"></script>
<script src="~/js/base/loader.js"></script>
<script src="~/js/mySpace/MySpaceService.js"></script>
<script src="~/js/user/UserProfileViewModel.js"></script>
-->


<script>
    /* $(document).ready(function () {
         let loader = new Loader({ getActionsUrl: domainPath + '/api/myspace/getActions' });
         loader.getActions()
             .done(function (data) {
                 debugger;
                 let service = new MySpaceService(data.actions);
                 let vewModel = new UserProfileViewModel(service);
                 vewModel.persanalDataVue.initialize();
             })
     })*/
    $(document).ready(function () {
        let loader = new Loader({ getActionsUrl: domainPath + '/api/admin/GetActions' });
        loader.getActions()
            .done(function (data) {
                let service = new UserProfileService(data.actions);
                let viewModel = new UserProfileViewModel(service);
                viewModel.persanalDataVue.initialize();
            });
    })
</script>

ITNews/Views/News/AddNews.cshtml
@{
    ViewData["Title"] = "News1";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Add news</h2>

@{ Html.RenderPartial("~/Views/Shared/_NewsDeatails.cshtml");}


<script src="~/js/section/Section.js"></script>
<script src="~/js/tag/Tag.js"></script>
<script src="~/js/news/NewsDetails/NewsDetailsViewModel.js"></script>
<script src="~/js/news/NewsDetails/NewsDetailsService.js"></script>
<script src="~/js/news/newsModel.js"></script>
<script src="~/js/base/loader.js"></script>
<script>
    $(document).ready(function () {
        let loader = new Loader({ getActionsUrl: domainPath + '/api/news/getActions' });
        loader.getActions()
            .done(function (data) {
                let service = new NewsDetailsService(data.actions);
                let viewModel = new NewsDetailsViewModel(service);
                viewModel.newsVue.initialize();
            })
    });
</script>

ITNews/Views/News/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>News</h1>

@{ Html.RenderPartial("~/Views/News/_NewsListPartial.cshtml");}


<script>
    $(document).ready(function () {
        let loader = new Loader({ getActionsUrl: domainPath + '/api/news/getActions' });
        loader.getActions()
            .done(function (data) {
                let service = new NewsService(data.actions);
                let viewModel = new NewsViewModel(service);
                viewModel.newsVue.initialize();
            });
    });
</script>

ITNews/Views/News/News.cshtml
@{
    ViewData["Title"] = "News";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>News</h1>

@{ Html.RenderPartial("~/Views/Shared/_NewsDeatails.cshtml");}


<script src="~/js/section/Section.js"></script>
<script src="~/js/tag/Tag.js"></script>
<script src="~/js/news/NewsDetails/NewsDetailsViewModel.js"></script>
<script src="~/js/news/NewsDetails/NewsDetailsService.js"></script>
<script src="~/js/news/newsModel.js"></script>
<script src="~/js/base/loader.js"></script>
<script>
    $(document).ready(function () {
        let loader = new Loader({ getActionsUrl: domainPath + '/api/news/getActions' });
        loader.getActions()
            .done(function (data) {
                let service = new NewsDetailsService(data.actions);
                let viewModel = new NewsDetailsViewModel(service);
                viewModel.newsVue.initialize();
            })
    });
</script>



<!--
<Div id="newsEntity">
    <div>
        <div class="form-group">
            <input id="newsName" style="cursor:auto" class="form-control" type="text" name="name" v-model="newsModel.name" readonly="readonly" />
        </div>
        <div class="form-group">
            <input id="newsDescription" style="cursor:auto" class="form-control" type="text" name="name" v-model="newsModel.description" readonly="readonly" />
        </div>
        <div class="form-group">
            <textarea id="newsTextContent" v-model="newsModel.content"></textarea>
        </div>
        <div class="form-group">
            <div style="text-align:right">
                <input type="button" class="btn btn-light" style="display:inline-block" name="name" value="Apply" v-on:click="editNews" />
            </div>
        </div>
    </div>
</Div>

<script src="~/js/markDown/MarkDownHelper.js"></script>
<script src="~/js/news/newsModel.js"></script>
<script src="~/js/news/NewsDetails/NewsDetailsViewModel.js"></script>

<script src="~/js/markDown/ace/1.1.3/ace.js"></script>
<script src="~/js/markDown/ace/1.1.3/ext-language_tools.js"></script>
<script src="~/js/markDown/ace/1.1.3/mode-markdown.js"></script>
<script src="~/js/markDown/ace/1.1.3/theme-tomorrow.js"></script>
<script src="~/js/markDown/marked/0.3.2/marked.min.js"></script>
<script src="~/js/markDown/jquery/2.1.3/jquery.min.js"></script>

<link href="~/css/markDown/bootstrap-markdown-editor.css" rel="stylesheet">
<script src="~/lib/bootstap_3.3.1/js/bootstrap.min.js"></script>
<script src="~/js/markDown/bootstrap-markdown-editor.js"></script>
-->

ITNews/Views/News/_NewsListPartial.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@


<div id="newsPage">
    <div class="row">
        <a v-if="hasAddNewsPermition()" class="btnAddNews btn btn-secondary" asp-controller="news" asp-action="addNews"><span>Add news</span></a>
        <div class="col-4">
            <div class="list-group" id="list-tab" role="tablist">
                <a v-for="section in sections" :href="'#list-profile'" v-on:click="sectionClick(section.id)"
                   class="list-group-item list-group-item-action" data-toggle="list">{{section.name}}</a>
            </div>
        </div>
        <div class="col-8">
            <div class="list-group">
                <div v-for="item in news" class="list-group-item list-group-item-action">
                    <a v-bind:href="item.url" class="list-group-item-action">
                        <div class="d-flex w-100 justify-content-between">
                            <h5 class="mb-1">{{item.name}}</h5>
                            <small>3 days ago</small>
                        </div>
                        <p class="mb-1">{{item.description}}</p>
                    </a>
                    <a class="linkDefault small" :href="userProfileUrl(item.authorId)">{{item.authorName}}</a>
                    <button v-on:click="deleteNewsClick(item.id)" v-if="hasEditPermissions(item)" type="button" class="close"><span aria-hidden="true">&times;</span></button>
                </div>

                <!--

            <a v-for="item in news" v-bind:href="item.url" class="list-group-item list-group-item-action">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">{{item.name}}</h5>
                    <small>3 days ago</small>
                </div>
                <p class="mb-1">{{item.description}}</p>
                <small>{{item.authorName}}</small>
            </a>
                >-->


            </div>
        </div>


    </div>



</div>



<link href="~/css/NewsListPartial.css" rel="stylesheet" />

<script src="~/js/News/NewsHub.js"></script>
<script src="~/js/signalr.min.js"></script>
<script src="~/js/News/newsModel.js"></script>
<script src="~/js/news/NewsService.js"></script>
<script src="~/js/base/loader.js"></script>
<script src="~/js/News/NewsViewModel.js"></script>
<script src="~/js/section/Section.js"></script>

ITNews/Views/Shared/_NavBar.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<div id="navMenu">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" asp-area="" asp-controller="News" asp-action="Index">News <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-area="admin" asp-controller="admin" asp-action="index">Admin</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        My Space
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" asp-area="" asp-controller="MySpace" asp-action="MyNews">My news</a>
                        <a class="dropdown-item" asp-area="" asp-controller="MySpace" asp-action="PersanalData">Persanal data</a>
                        @{/*
                                  <a class="dropdown-item" href="#">Another action</a>
                                  <div class="dropdown-divider"></div>
                                  <a class="dropdown-item" href="#">Something else here</a>
                                  */
                        }
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
            <ul class="navbar-nav ml-auto">
                <li v-if="userIsNotAuthorize">
                    <a class="nav-link" asp-area="" asp-controller="Authorize" asp-action="Login">LogIn</a>
                </li>
                <li v-if="userIsNotAuthorize">
                    <a class="nav-link" asp-area="" asp-controller="Authorize" asp-action="Registration">Registration</a>
                </li>
                <li class="nav-item dropdown" v-if="userIsAuthorize">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span>{{email}}</span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" asp-area="" asp-controller="" asp-action="">do nothing</a>
                        <a class="dropdown-item" asp-area="" asp-controller="MySpace" asp-action="MyNews">My news</a>
                        <a class="dropdown-item" asp-area="" asp-controller="MySpace" asp-action="PersanalData">Persanal data</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" asp-area="" v-on:click="logOut">LogOut</a>
                        @{/*
                                    <a class="dropdown-item" href="#">Another action</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="#">Something else here</a>
                                    */
                        }
                    </div>
                </li>
            </ul>
        </div>
    </nav>
</div>

ITNews/Views/Shared/_NavBar_bootstrap3.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@




<nav class="navbar navbar-default">
    <div id="navMenu" class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">ITNews</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a asp-area="" asp-controller="News" asp-action="Index">News</a>
                </li>
                <li>
                    <a asp-area="" asp-controller="" asp-action="">temp...</a>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">My Space <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a asp-area="" asp-controller="MySpace" asp-action="MyNews">My news</a></li>
                        <li><a asp-area="" asp-controller="MySpace" asp-action="PersanalData">Persanal data</a></li>
                        @{/*<li role="separator" class="divider"></li>*/ }
                    </ul>
                </li>
            </ul>
            <form class="navbar-form navbar-left">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Search">
                </div>
                <button type="submit" class="btn btn-default">Submit</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li v-if="userIsNotAuthorize">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Authorize" asp-action="Login">LogIn</a>
                </li>
                <li v-if="userIsNotAuthorize">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Authorize" asp-action="Registration">Registration</a>
                </li>
                <li><a href="#">Link</a></li>
                <li class="dropdown" v-if="userIsAuthorize">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Will be User Name <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">do nothing</a></li>
                        <li><a asp-area="" asp-controller="MySpace" asp-action="MyNews">My news</a></li>
                        <li><a asp-area="" asp-controller="MySpace" asp-action="MyNews">Persanal data</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a class="nav-link text-dark" asp-area="" v-on:click="logOut">LogOut</a></li>
                    </ul>
                </li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>